### ISSUE TITLE
Source of NOx sensor

### ISSUE THREAD

**Issue by luetzel** [rmh78/NO2-Measurement#1]
Howdy,
interesting project. Where did you buy the NOx breakout boards? Your link seems to point only to the bare NO2-A43F sensor, but not to the sensors seen on the picture with the breadboard.
Cheers,
/luetzel

**Comment by rmh78** [comment]
Bought all the NO2 sensor stuff at Alphasense Ltd Sensor Technology House (http://www.alphasense.com/index.php/air/):
1) 000-0ISB-02 - 4-electrode ISB (NO2, OX)
2) 000-0NO2-B43F - Nitrogen Dioxide B Sensor - NO2-B43F-
3) 000-0ISB-KIT - ISB Fitting Kit
