### ISSUE TITLE
Please give circuit diagram for NO2 and ASD1115 and with controller

### ISSUE THREAD

**Issue by samueldinesh** [rmh78/NO2-Measurement#2]
**Please give circuit diagram for NO2 and ASD1115 and with controller**

An image is not clear to view the wire connections. The circuit diagram is very useful.

### **Thank you**

**Comment by rmh78** [comment]
The NO2 sensor of Alphasense comes with an instruction how to connect. 
I do not have any circuit diagram for my project.
